### ISSUE TITLE
Aktualisiert nicht mehr

### ISSUE THREAD

**Issue by dominik-ba** [ViMaSter/rbtv_schedule#2]
wenn das plugin seit sonntag installiert ist, aktualisiert sich die anzeige nicht mehr und bei neu "installation" bleibt die ladeanzeige dauerhaft stehen...

Das sagt der debugger:
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
core.js:172 Uncaught TypeError: Cannot read property 'slice' of undefined

**Comment by ViMaSter** [comment]
Auf Development-Branch bereits nicht mehr reproduzierbar.
